# Generated by Django 3.2.3 on 2022-03-29 04:54

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('sex', models.CharField(choices=[('male', '男'), ('female', '女'), ('secrecy', '保密')], default='secrecy', max_length=7)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('publishDate', models.DateField()),
                ('totalCount', models.PositiveIntegerField(default=0)),
                ('borrowCount', models.PositiveIntegerField(default=0)),
                ('description', models.TextField(blank=True, null=True)),
                ('isbn', models.CharField(max_length=13, validators=[django.core.validators.RegexValidator('^97[89][0-9]{10}$', '请填写正确的ISBN')])),
                ('classification', models.CharField(max_length=32)),
                ('enterDate', models.DateField()),
                ('author', models.ManyToManyField(to='app01.Author')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Publish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, validators=[django.core.validators.MinLengthValidator(1)])),
                ('addr', models.CharField(blank=True, max_length=32, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Reader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate', models.CharField(max_length=10, unique=True, validators=[django.core.validators.RegexValidator('^[0-9]{10}$', '借书证号只能为10位数字')])),
                ('name', models.CharField(max_length=16)),
                ('password', models.CharField(max_length=16)),
                ('availableBooks', models.IntegerField(default=4)),
                ('borrowedBooks', models.IntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BorrowingLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('borrow', models.BooleanField(default=True)),
                ('returned', models.BooleanField(default=False)),
                ('borrowDate', models.DateField()),
                ('returnedDate', models.DateField()),
                ('actualDate', models.DateField(blank=True, null=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app01.book')),
                ('reader', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app01.reader')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='book',
            name='publish',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app01.publish'),
        ),
    ]
