# Generated by Django 3.2.3 on 2022-03-30 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0003_alter_borrowinglog_actualdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowinglog',
            name='borrowDate',
            field=models.DateTimeField(),
        ),
    ]
