# Generated by Django 3.2.3 on 2022-03-31 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0004_alter_borrowinglog_borrowdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowinglog',
            name='days',
            field=models.PositiveIntegerField(default=60),
        ),
        migrations.AlterField(
            model_name='borrowinglog',
            name='returnedDate',
            field=models.DateTimeField(),
        ),
    ]
